language: java
sudo: required

cache:
  directories:
    - $HOME/.m2

jdk:
  - oraclejdk8
  - oraclejdk9

services:
  - docker


#branches:
#  only:
#    - master
#  except:
#    - Nick

notifications:
  email: false



script:
  - ls
  - mvn pmd:pmd --log-file pmd-log.txt
  - cat pmd-log.txt
  - ls
  - mvn exec:java
  - mvn -Dtest=* test
  - echo $TRAVIS_JDK_VERSION
  - echo $TRAVIS_BUILD_DIR
#  - cd $HOME
#  - ls

