language: java
sudo: required

cache:
  directories:
    - $HOME/.m2

jdk:
  - oraclejdk8
  - oraclejdk9

services:
  - docker


#branches:
#  only:
#    - master
#  except:
#    - Nick

notifications:
  email: false



script:
  - ls
  - mvn pmd:pmd
  - ls
  - mvn exec:java
  - mvn -Dtest=* test
  - echo $TRAVIS_JDK_VERSION
  - cd target
  - ls
  - cd surefire-reports
  - cd maven-status
  - ls

