language: java
#sudo: required only required when you use sudo commands or docker
sudo: false

cache:
  directories:
    - $HOME/.m2

jdk:
  - oraclejdk8
  - oraclejdk9



#services:
#  - docker


#branches:
#  only:
#    - master
#  except:
#    - Nick

notifications:
  email: false



script:
#  - cat target/pmd.xml
  - ls $HOME/.m2/repository
#  - ls target
#  - ls
#  - mvn pmd:pmd
#  - ls
  - mvn exec:java
  - mvn -Dtest=* test
  - echo $TRAVIS_JDK_VERSION
  - echo $TRAVIS_BUILD_DIR
#  - cd $HOME
  - ls
