language: java
sudo: false

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk7

#branches:
#  only:
#    - master
#  except:
#    - Nick

notifications:
  email: false

script:
  - mvn -Dtest=* test
  - echo hello
