language: java
sudo: false

cache:
  directories:
    - $HOME/.m2

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk7

#branches:
#  only:
#    - master
#  except:
#    - Nick

notifications:
  email: false

script:
  - mvn -Dtest=* test

