language: java
sudo: required

cache:
  directories:
    - $HOME/.m2

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk7

services:
  - docker


#branches:
#  only:
#    - master
#  except:
#    - Nick

notifications:
  email: false

before_install:
  - wget -q -O - https://github.com/zaproxy/zaproxy/releases/download/2.4.3/ZAP_2.4.3_Linux.tar.gz | tar zxf - -C /opt
    ln -s /opt/ZAP_2.4.3 /opt/zap

script:
  - mvn exec:java
  - mvn -Dtest=* test
  - echo $TRAVIS_JDK_VERSION

